version: '3.1'

services:

  file-dump:
    build:
      context: ./src/convertor/
    volumes:
      - ./data/:/data
      - ./output/:/output
    command: ["./create_dump.sh", "create_file_dump.py"]
