#!/usr/bin/python3

# Last updated 25/04/2019 11:30
DOCUMENT_TYPES = (
    ("Nota", "Nota aan de Vlaamse Regering", "Het belangrijkste, inleidende, kaderende, verantwoordende document bij een ontwerp van besluit, ontwerp van decreet of beslissingsdocument."),
    ("MvT", "Memorie van Toelichting", "Toelichtend document bij een tekst voor een decreet"),
    ("BVR", "Besluit van de Vlaamse Regering", "Regelgevend document"),
    ("VOBVR", "Voorontwerp van BVR", "Voorontwerp van een Besluit van de Vlaamse Regering"),
    ("OBVR", "Ontwerp van BVR", "Ontwerp van een Besluit van de Vlaamse Regering"),
    ("OD", "Ontwerpdecreet van Vlaamse Regering", "Regelgevend document"),
    ("VOD", "Voorontwerp van decreet", "Voorontwerp voor een decreet"),
    ("Decreet", "Te bekrachtigen decreet", "Het decreet dat terugkomt van het VP en moet bekrachtigd worden"),
    ("MB", "Ministerieel besluit", "Een besluit van een Minister op basis van delegatie."),
    ("SWA", "Samenwerkingsakkoord", "Regelgevend document"),
    ("SWO", "Samenwerkingsovereenkomst", "Regelgevend document"),
    ("Verslag", "Verslag aan de Regering", "Toelichtend document bij een BVR"),
    ("Bijlage", "Bijlage", "Toelichtende, verklarende, stavende bijlage"),
    ("BijlageInfo", "Bijlage(n) ter informatie", "Hierover wordt in principe niet beslist."),
    ("BijlageNota", "Bijlage ter beslissing", "Een bijlage die een beslissing behoeft."),
    ("Mededeling", "Mededeling", "Niet te verwarren met de procedurestap/dossiertype \"mededeling\".  Dit gaat over een document."),
    ("OMZ", "Omzendbrief", "Omzendbrief"),
    ("Overeenkomst", "Overeenkomst", "Is een bilaterale overeenkomst, toezegging, dading, enz."),
    ("PV", "Proces Verbaal", "Een verslag. Bijvoorbeeld van een gunning, een audit, enz..."),
    ("BF", "Beslissingsfiche", "Beslissingsfiche"),
    ("Notule", "Notule", "Verslag van de vergadering"),
    ("Beleidsbrief", "Beleidsbrief"),
    ("Beleidsnota", "Beleidsnota"),

    ("IF", "Advies van Inspectie Financiën"),
    ("BA", "Begrotingsakkoord van de minister van begroting"),
    ("RvS", "Advies Raad van State"),
    ("Aku BZ", "Akkoord Bestuurszaken"),
    ("Advies AgO", "Advies agentschap overheidspersoneel"),
    ("Advies", "Advies", "Verzamelterm voor de adviezen bij SAR's en andere"),
    ("Protocol", "Protocol", "Resultaat onderhandelingen in overlegorganen"),
    ("Motie", "Motie", "Document van het Vlaams Parlement dat bij mededeling aan de regering wordt voorgelegd"),
    ("Resolutie", "Resolutie", "Document van het Vlaams Parlement dat bij mededeling aan de regering wordt voorgelegd"),

    ("Concept", "Conceptnota", "reflectie-en consultatiedocument"),
    ("Groenboek", "Groenboek", "reflectie-en consultatiedocument"),
    ("Witboek", "Witboek", "beleidsverklaring inzake een beleidskwestie"),

    ("Visienota", "Visienota", "beperkte beleidsverklaring inzake een beleidskwestie"),

    ("Errat", "Erratum"),
    ("Arrest", "Arrest"),
    ("Besluit AG", "Besluit van een administrateur-generaal"),
    ("Besluit SG", "Besluit van een secretaris-generaal"),
    ("Besluit HA", "Besluit Hoofd Agentschap"),
    ("Besluit RvB", "Besluit Raad van Bestuur"),
    ("Besluit AH", "Besluit Afdelingshoofd"),
    ("Besluit HD", "Besluit HoofdDepartement"),
    ("Bericht", "Bericht"),
)
