#!/usr/bin/python3

GOVERNMENT_FUNCTIONS = (
    "het algemeen regeringsbeleid", # 'De Vlaamse minister, bevoegd voor ...'
    "het algemeen communicatiebeleid",
    "de interne audit van de Vlaamse administratie",
    "de gewestelijke aspecten in zake de overheidsopdrachten en de erkenning van aannemers",
    "de financiële tegemoetkoming naar aanleiding van schade veroorzaakt door algemene rampen",
    "het reguleringsmanagement",
    "de gerechtelijke procedure voor onteigening ten algemenen nutte",

    "het buitenlands beleid en de Europese aangelegenheden",
    "de ontwikkelingssamenwerking",
    "het afzet- en uitvoerbeleid",
    "het aantrekken van buitenlandse investeringen",
    "controle op de handel in strategische goederen",
    "het onroerend erfgoed",
    "het protocol",

    "het onderwijs",
    "het gebruik van de talen voor het onderwijs",
    "de voorschoolse vorming in de peutertuinen",
    "de post- en parascolaire vorming",
    "de sociale promotie",
    "de basiseducatie voor laaggeschoolde volwassenen",
    "het volwassenenonderwijs",
    "de structurele financiering van het wetenschappelijk onderzoek aan de universiteiten en de hogescholen",
    "de studiefinanciering",
    "de leerlingenbegeleiding met inbegrip van het medisch schooltoezicht",
    "de coördinatie van het vormingsbeleid",
    "de stelsels van alternerend leren",

    "de financiën en de begrotingen",
    "de fiscaliteit",
    "de gewestelijke aspecten van het kredietbeleid",
    "de authentificering van de handelingen met een onroerend karakter",
    "het energiebeleid",

    "de binnenlandse aangelegenheden",
    "het beleid inzake onthaal en integratie van inwijkelingen",
    "de huisvesting",
    "de sociale economie",
    "het algemeen beleid inzake personeel en organisatieontwikkeling in de Vlaamse administratie",
    "het algemeen beleid inzake de facilitaire dienstverlening en het vastgoedbeheer in de Vlaamse administratie",
    "het algemeen beleid inzake informatie- en communicatietechnologie in de Vlaamse administratie",
    "het e-government",
    "het gelijkekansenbeleid",
    "de coördinatie van het armoedebeleid",
    "de informatiemaatschappij, het structureren, opslaan, uitwisselen  en ontsluiten van informatie en de infolijn;",
    "de uitbouw van een geografische informatie infrastructuur",

    "het mobiliteitsbeleid, de openbare werken en het vervoer",
    "het vervoer van mindervaliden",
    "het verkeersveiligheidsbeleid",
    "de coördinatie van het beleid met betrekking tot de Vlaamse Rand rond Brussel",
    "het toerisme",
    "het dierenwelzijn",

    "de bijstand aan personen",
    "het gezondheidsbeleid",
    "de gezinsbijslagen",
    "de justitiehuizen",
    "het elektronisch toezicht",

    "het tewerkstellingsbeleid",
    "het gebruik van de talen voor de sociale betrekkingen",
    "de professionele vorming",
    "de economie",
    "het wetenschapsbeleid",
    "het technologisch innovatiebeleid",
    "de lichamelijke opvoeding, de sport en het openluchtleven",
    "de medisch verantwoorde sportbeoefening",

    "het leefmilieu en het waterbeleid",
    "de landinrichting en het natuurbehoud"
    "de natuurlijke rijkdommen",
    "de ruimtelijke ordening",
    "de landbouw",
    "de land- en tuinbouwvorming",
    "het afzet- en uitvoerbeleid van landbouw-, tuinbouw- en visserijproducten",
    "het plattelandsbeleid",

    "de culturele aangelegenheden",
    "het mediabeleid",
    "de coördinatie van het kinderrechtenbeleid",
    "de filmkeuring",
    "de coördinatie van het beleid met betrekking tot Brussel-Hoofdstad",
)