from rdflib import Namespace

MU = Namespace("http://mu.semte.ch/vocabularies/core/")
EXT = Namespace("http://mu.semte.ch/vocabularies/ext/")
TMP = Namespace("http://mu.semte.ch/vocabularies/tmp/")
EXPORT = Namespace("http://mu.semte.ch/vocabularies/ext/export/")
VALIDATION = Namespace("http://mu.semte.ch/vocabularies/validation/")

from rdflib.namespace import RDF
RDFS = Namespace("https://www.w3.org/2000/01/rdf-schema#")

OC = Namespace("http://mu.semte.ch/vocabularies/ext/oc")
BESLUIT = Namespace("http://data.vlaanderen.be/ns/besluit#")
BESLUITVORMING = Namespace("http://data.vlaanderen.be/ns/besluitvorming#")
GENERIEK = Namespace("http://data.vlaanderen.be/ns/generiek#")
MANDAAT = Namespace("http://data.vlaanderen.be/ns/mandaat#")
ORGANISATIE = Namespace("https://data.vlaanderen.be/ns/organisatie#")
PERSOON = Namespace("http://data.vlaanderen.be/ns/persoon#")

ADMS = Namespace("http://www.w3.org/ns/adms#")
CPSV = Namespace("http://purl.org/vocab/cpsv#")
DBPEDIA = Namespace("http://dbpedia.org/ontology/")
DCAT = Namespace("http://www.w3.org/ns/dcat#")
DCT = Namespace("http://purl.org/dc/terms/")
DUL = Namespace("http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#")
ELI = Namespace("http://data.europa.eu/eli/ontology#")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
M8G = Namespace("http://data.europa.eu/m8g/")
NAO = Namespace("http://www.semanticdesktop.org/ontologies/2007/08/15/nao#")
NFO = Namespace("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
NIE = Namespace("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
ORG = Namespace("http://www.w3.org/ns/org#")
OWL = Namespace("http://www.w3.org/2002/07/owl#")
PAV = Namespace("http://purl.org/pav/")
PERSON = Namespace("http://www.w3.org/ns/person#")
PROV = Namespace("http://www.w3.org/ns/prov#")
REGORG = Namespace("https://www.w3.org/ns/regorg#")
SCHEMA = Namespace("http://schema.org/")
SKOS = Namespace("http://www.w3.org/2004/02/skos/core#")
